ConversorMoneda/Models/ErrorViewModel.cs
using System;

namespace ConversorMoneda.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConversorMoneda/Controllers/CurrencyController.cs
using Application.Services;
using Application.ViewModels;
using ConversorMoneda.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConversorMoneda.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ILogger<CurrencyController> _logger;
        private readonly CurrenciesViewModel vm = new();
        private readonly CurrencyService service = new();
        public CurrencyController(ILogger<CurrencyController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(vm);
        }
        [HttpPost]
        public IActionResult Index(CurrenciesViewModel currencies)
        {
            currencies.ValorDivisa = service.CalculateCurrency(currencies);
            return View(currencies);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConversorMoneda/Views/Currency/Index.cshtml
@model Application.ViewModels.CurrenciesViewModel
@{
    ViewData["Title"] = "Home";
}

<div class="row justify-content-center text-white p-3 m-1 rounded-3 " style="background-color: #293462">
    <form method="post" asp-controller="Currency" asp-action="Index" class="col-6">
        <div class="mb-3">
            <label asp-for="De" class="form-label">De:</label>
            <select asp-for="De" class="form-select" aria-label="Default select example">
                <option value="1">Pesos DOM</option>
                <option selected value="2">Dolar USD</option>
                <option value="3">Euro EUR</option>
            </select>
        </div>
        <div class="mb-3">
            <label asp-for="A" class="form-label">A:</label>
            <select asp-for="A" class="form-select" aria-label="Default select example">
                <option value="1">Pesos DOM</option>
                <option value="2">Dolar USD</option>
                <option value="3">Euro EUR</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="Cantidad">Cantidad:</label>
            <input type="number" step="any" asp-for="Cantidad" class="form-control" min="1">
        </div>
        <div class="row justify-content-center">
            <button type="submit" class="btn text-center text-white mb-3 col-sm-4" style="background-color: #242f9b">Convert</button>
        </div>
    </form>
    @if (Model.ValorDivisa != 0)
    {
        <div class="card col-8" style="background-color: #205375">
            <div class="card-body">
                <h3 class="text-center">Resultado: $ @Model.ValorDivisa</h3>
            </div>
        </div>
    }
</div>

ConversorMoneda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Conversor Moneda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#15133c">
            <div class="container justify-content-center">
                <a class="navbar-brand text-white text-capitalize" asp-area="" asp-controller="Currency" asp-action="Index">CONVERTIDOR DE MONEDA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.Now.Year - Conversor Moneda
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>